// File: android/build.gradle

buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Android Gradle Plugin
       // classpath 'com.android.tools.build:gradle:8.3.0'
        // Google Services plugin (Firebase, etc.)
       // classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath 'com.google.gms:google-services:4.3.15'
        // Kotlin Gradle Plugin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Redirect all modules’ build outputs into a centralized folder one level above.
// (זה מאפשר ששום מודול לא יבנה בתוך תיקיית android/app/build אלא ב־../build/…)
rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
// ודא שכל התרחישים של build במודול :app יורצים לפני build של שאר התתי־פרוייקטים
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
