// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8uI6BP5MnuyNV0bbulJvVaZv2fQA3yTc',
    appId: '1:834280724593:web:361b71f863f8a65fdc23d0',
    messagingSenderId: '834280724593',
    projectId: 'therapyrobot-a8d2f',
    authDomain: 'therapyrobot-a8d2f.firebaseapp.com',
    storageBucket: 'therapyrobot-a8d2f.firebasestorage.app',
    measurementId: 'G-26LLZ4ESLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU_IQc47pTJBjCJpNGy3sBElVi1_3FZS0',
    appId: '1:834280724593:android:66501383b1ad11f0dc23d0',
    messagingSenderId: '834280724593',
    projectId: 'therapyrobot-a8d2f',
    storageBucket: 'therapyrobot-a8d2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjM3Z4qofwGyMFLlK12q9kXKiU3UjYdms',
    appId: '1:834280724593:ios:53350c77f92b7f16dc23d0',
    messagingSenderId: '834280724593',
    projectId: 'therapyrobot-a8d2f',
    storageBucket: 'therapyrobot-a8d2f.firebasestorage.app',
    iosBundleId: 'com.example.psychologicalCounselor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjM3Z4qofwGyMFLlK12q9kXKiU3UjYdms',
    appId: '1:834280724593:ios:53350c77f92b7f16dc23d0',
    messagingSenderId: '834280724593',
    projectId: 'therapyrobot-a8d2f',
    storageBucket: 'therapyrobot-a8d2f.firebasestorage.app',
    iosBundleId: 'com.example.psychologicalCounselor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXP9fkCQUuWTcvMVHsSnz7rDQS7jxLoNg',
    appId: '1:834280724593:web:07e53da653f1a720dc23d0',
    messagingSenderId: '834280724593',
    projectId: 'therapyrobot-a8d2f',
    authDomain: 'therapyrobot-a8d2f.firebaseapp.com',
    storageBucket: 'therapyrobot-a8d2f.firebasestorage.app',
    measurementId: 'G-2CQCRXVYD0',
  );

}